version: '3.7'

services:
  license-service:
    image: license-service:latest

    ports:
      - "8080:8080"

    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CONFIG_IMPORT=configserver:http://localhost:8071"
    networks:
      backend:
        aliases:
          - "licenseservice"

networks:
    backend:
      driver: bridge

