spring:
  application:
    name: license-service
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8071"

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true

  instances:
    licenseService:
      registerHealthIndicator: true
      sliding-window-size: 5
      permitted-number-of-calls-in-half-open-state: 3
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      automatic-transition-from-open-to-half-open-enabled: true
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
    organizationService:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 6
      ringBufferSizeInHalfOpenState: 4
      waitDurationInOpenState: 20s
      failureRateThreshold: 60