spring:
  application:
    name: organization-service
  config:
    import: "configserver:${CONFIGSERVER_URI}"
  main:
    allow-circular-references: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/spmia-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: ostock
      principal-attribute: principal_username

logging:
  level:
    org.springframework.security: debug