server:
  port: 8081
jpa:
  hibernate:
    ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_URI}"
  instance:
    prefer-ip-address: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
